### ISSUE TITLE
Question:How much effort to use sixel as preview library?

### ISSUE THREAD

**Issue by dedguy21** [emsquid/preview.xplr#2]
I use kitty terminal so it won't effect me as much, but in order to  preview images in alacritty or wezterm, I use sixel, it's a darn good lib (better than python's ueberzug) for previewing images in the terminal.

**Comment by emsquid** [comment]
> I use kitty terminal so it won't effect me as much, but in order to  preview images in alacritty or wezterm, I use sixel, it's a darn good lib (better than python's ueberzug) for previewing images in the terminal.

Hey! I will check this and see how it works before answering you, I might be occupied for a bit because of school but I will definitely work on it whenever I get some free time, in around a week I'd say :)
